FROM python:3.11-slim

WORKDIR /app

COPY .streamlit/ .streamlit/
COPY config/ config/
COPY frontend/ frontend/
COPY requirements-frontend.txt .

RUN pip install -r requirements-frontend.txt

COPY app.py .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]