# Base image for FastAPI
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy backend files

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    cmake \
    libopenblas-dev \
    libomp-dev \
    && rm -rf /var/lib/apt/lists/*
    
COPY . .
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose the default FastAPI port
EXPOSE 8000

# Run the FastAPI app
CMD ["uvicorn", "middleware:app", "--host", "0.0.0.0", "--port", "8000"]