from setuptools import setup, find_packages

setup(
    name="llmmiddleware",
    version="0.1.0",
    description="PocketFlow-based middleware for SQL generation and data visualization",
    author="",
    author_email="",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
    install_requires=[
        "fastapi>=0.103.1",
        "sentence_transformers",
        "faiss-cpu",
        "python-dotenv",
        "uvicorn>=0.23.2",
        "pandas",
        "numpy",
        "streamlit>=1.25.0",
        "aisuite>=0.1.11",
        "openai",
        "groq",
        "anthropic",
        "pymilvus",
        "langchain",
        "langchain-community",
        "pydantic",
        "orjson",
        "plotly",
        "matplotlib",
        "pyyaml",
        "requests",
    ],
) 