llms:
  - name: "LLAMA3.2"
    provider: "groq"
    model: 'llama-3.2-3b-preview'
  - name: "OpenAI gpt-3.5-turbo"
    provider: "openai"
    model: "gpt-3.5-turbo"
  - name: "OpenAI GPT-4o"
    provider: "openai"
    model: "gpt-4o"
  - name: "Anthropic Claude 3.5 Sonnet"
    provider: "anthropic"
    model: "claude-3-5-sonnet-20240620"
  - name: "Azure/OpenAI GPT-4o"
    provider: "azure"
    model: "gpt-4o"
  - name: "Huggingface/Mistral 7B"
    provider: "huggingface"
    model: "mistralai/Mistral-7B-Instruct"