predefinedqustions:
  # ยอดขายและประสิทธิภาพของสินค้า
  - question: ยอดขายและประสิทธิภาพของสินค้า - สินค้าหรือหมวดหมู่ใดสร้างรายได้และกำไรมากที่สุด?
  - question: ยอดขายและประสิทธิภาพของสินค้า - แบรนด์ใดทำผลงานได้ดีที่สุดในแต่ละภูมิภาคหรือสาขา?
  - question: ยอดขายและประสิทธิภาพของสินค้า - แนวโน้มตามฤดูกาลของยอดขายสินค้าในแต่ละหมวดหมู่เป็นอย่างไร?

  # พฤติกรรมการทำธุรกรรม
  - question: พฤติกรรมการทำธุรกรรม - ขนาดตะกร้าซื้อเฉลี่ยต่อรายการต่อสาขาหรือจังหวัดเป็นเท่าไร?
  - question: พฤติกรรมการทำธุรกรรม - สมาชิกที่มีบัตรสะสมแต้มใช้จ่ายต่อการเข้าชมมากกว่าลูกค้าทั่วไปหรือไม่?
  - question: พฤติกรรมการทำธุรกรรม - สาขาใดมีอัตราการคืนสินค้าหรือขอเงินคืนสูงที่สุด?

  # ข้อมูลเชิงลึกของลูกค้าและสมาชิก
  - question: ข้อมูลเชิงลึกของลูกค้าและสมาชิก - ยอดขายทั้งหมดมีสัดส่วนมาจากสมาชิกบัตรสะสมแต้มเท่าใด?
  - question: ข้อมูลเชิงลึกของลูกค้าและสมาชิก - กลุ่มสมาชิกใดที่สร้างผลกำไรมากที่สุด?
  - question: ข้อมูลเชิงลึกของลูกค้าและสมาชิก - กลยุทธ์การรักษาสมาชิกกลุ่มมูลค่าสูงที่มีประสิทธิภาพคืออะไร?